project:
  type: website
  output-dir: docs

website:
  title: "Junhui He"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: publication.qmd
      - href: software.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: 
  render-on-save: true



